on:
 workflow_dispatch:
   inputs:
     enviroment:
       description: "Choose Enviroment"
       required: true
       default: "staging"
       type: choice
       options:
         - stagging
         - production   
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: echo "Deploying Application...."
